# ***Python Capstone Project***

### *TASK 1: Please make three dataframe in python and save them as three .csv files.*

In [102]:
# importing required packages

import pandas as pd
import numpy as np

In [103]:
# Entering the data

project_data = {
     'ID': ['A001', 'A002', 'A003', 'A004', 'A005', 'A002','A005', 'A003', 'A001','A003', 'A001','A004', 'A004', 'A005'],
    'Project':['Project 1','Project 2','Project 3','Project 4','Project 5','Project 6','Project 7','Project 8','Project 9','Project 10','Project 11','Project 12','Project 13','Project 14'],
    'Cost':[1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 350000, np.nan, 300000, 2000000, 1000000, 3000000, 200000],
    'Status':['Finished', 'Ongoing', 'Finished', 'Ongoing', 'Finished', 'Failed', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Finished']
}

employee_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Name': ['John Alter', 'Alice Luxumberg','Tom Sabestine','Nina Adgra','Amy Johny'],
    'Gender':['M','F','M','F','F'],
    'City':['Paris','London','Berlin','Newyork','Madrid'],
    'Age':[25,27,29,31,30]    
}

seniority_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Designation Level': ['2', '2', '3', '2', '3']
}

In [104]:
# passing the data to pandas dataframes

project_df = pd.DataFrame(project_data)
employee_df = pd.DataFrame(employee_data)
senior_data_df = pd.DataFrame(seniority_data)

In [105]:
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [106]:
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [107]:
senior_data_df

     ID Designation Level
0  A001                 2
1  A002                 2
2  A003                 3
3  A004                 2
4  A005                 3

In [108]:
# saving the dataframes as csv files

project_df.to_csv('project.csv', index=False)
employee_df.to_csv('employee.csv', index=False)
senior_data_df.to_csv('senior.csv', index=False)

### *TASK 2: The cost column in the dataframe “Project” has some missing values. Compute these missing values. Replace the missing values by running average. Use the “For” loop for this task.*

In [109]:
# importing the saved csv files

project_df = pd.read_csv('/kaggle/working/project.csv')
employee_df = pd.read_csv('/kaggle/working/employee.csv')
senior_data_df = pd.read_csv('/kaggle/working/senior.csv')

In [110]:
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [111]:
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [112]:
senior_data_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [113]:
# calculating running average for missing values

total = 0
for i in range(len(project_df)):
    # using iloc to access values of 'Cost' column
    if pd.isna(project_df.iloc[i, 2]):
        average = total/(i)
        project_df.iloc[i, 2] = average
        total += project_df.iloc[i, 2]
    else:
        total += project_df.iloc[i, 2]

In [114]:
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

### *Task 3: Split the name column in the Employee dataframe into two new columns “First Name”, and “Last Name” and remove the older “name” column.*

In [115]:
# creating new columns 

employee_df['First Name'] = employee_df['Name'].str.split(' ').str[0]
employee_df['Last Name'] = employee_df['Name'].str.split(' ').str[1]

In [116]:
# dropping old 'Name' column

employee_df.drop(columns=['Name'], inplace=True)

In [117]:
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

### *Task 4: Join all three dataframes in one single dataframe. Name it “Final”*

In [118]:
# joining the dataframes

df = pd.merge(project_df, employee_df, on='ID', how='inner')
final = pd.merge(df, senior_data_df, on='ID', how='inner')

In [119]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3

### *Task 5: A new bonus column in the Final dataframe. Give a 5% bonus concerning project cost only to employees who have finished the projects.*

In [120]:
# using numpy for creating new column based on condition
final['Bonus'] = np.where(final['Status'] == 'Finished', final['Cost']*0.05, np.nan)

In [121]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,NaN
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,NaN
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,NaN
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,NaN
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,NaN
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,NaN
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,NaN
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

### *Task 6: Demote the designation level by 1, whose projects have status “fail”. Delete the employees record whose designation level is above 4.*

In [122]:
# demoting designation level by 1 i.e. Designation Level + 1

final['Designation Level'] = np.where(
    final['Status'] == 'Failed', 
    final['Designation Level'] + 1, 
    final['Designation Level']
)

In [123]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,NaN
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,NaN
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,3,NaN
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,4,NaN
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,NaN
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,3,NaN
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,NaN
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

In [124]:
# deleting employee records for designation level > 4

records_to_delete = final[final['Designation Level'] > 4].index
final = final.drop(records_to_delete)

In [125]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,NaN
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,NaN
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,3,NaN
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,4,NaN
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,NaN
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,3,NaN
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,NaN
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

### *Task 7: Add “Mr.” and “Mrs.” to the first name column and drop the gender column.*

In [126]:
# Adding 'mr' and 'mrs' to the first name

final['First Name'] = np.where(
    final['Gender'] == 'M', 
    'Mr. ' + final['First Name'], 
    'Mrs. ' + final['First Name']
)

final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Mrs. Alice,Luxumberg,2,NaN
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,NaN
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Mrs. Alice,Luxumberg,3,NaN
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Mrs. Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Mr. Tom,Sabestine,4,NaN
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,Mr. John,Alter,2,NaN
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,Mr. John,Alter,3,NaN
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,NaN
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Mrs. Amy,Johny,3,10000.0

In [127]:
# dropping gender column

final.drop(columns=['Gender'], inplace=True)

In [128]:
final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,NaN
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,NaN
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,3,NaN
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,4,NaN
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,NaN
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,3,NaN
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,NaN
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,10000.0

### *Task 8: Promote designation level by 1 for the employees whose age is more than 29 years using IF condition.*

In [129]:
# Promote designation level by 1 if age > 29 i.e. Desgination Level - 1

final['Designation Level'] = final.apply(
    lambda x: x['Designation Level']-1 if x['Age'] > 29 else x['Designation Level'],
    axis=1
)

final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,NaN
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,NaN
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,2,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,3,NaN
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,2,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,4,NaN
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,NaN
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,3,NaN
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,NaN
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,2,10000.0

### *Task 9: Add the cost of all projects for each Employee and save it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost*

In [130]:
# Total Cost of projects per employee

TotalProjCost = final.groupby(['ID', 'First Name']).agg({'Cost': 'sum'}).reset_index()
TotalProjCost.rename(columns={'Cost': 'Total Cost'}, inplace=True)
TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

### *Task 10: Print all the employee details whose city name contains the letter “o” in it.*

In [131]:
# Employee details where city contains letter 'o'

contain_o = final[final['City'].str.contains('o')]
contain_o

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,NaN
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,NaN
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,3,NaN
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,NaN
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000.0

In [132]:
# printing details of the employees

print(contain_o)

      ID     Project       Cost    Status     City  Age  First Name  \
1   A002   Project 2  2000000.0   Ongoing   London   27  Mrs. Alice
3   A004   Project 4  5500000.0   Ongoing  Newyork   31   Mrs. Nina
5   A002   Project 6   680000.0    Failed   London   27  Mrs. Alice
11  A004  Project 12  1000000.0   Ongoing  Newyork   31   Mrs. Nina
12  A004  Project 13  3000000.0  Finished  Newyork   31   Mrs. Nina

    Last Name  Designation Level     Bonus
1   Luxumberg                  2       NaN
3       Adgra                  1       NaN
5   Luxumberg                  3       NaN
11      Adgra                  1       NaN
12      Adgra                  1  150000.0